### ISSUE TITLE
SharedLibraryLoader subproject

### ISSUE THREAD

**Issue by PokeMMO** [libgdx/gdx-jnigen#2]
Instead of having two implementations SharedLibraryLoader and JniGenSharedLibraryLoader we should probably unify to a single implementation with no other dependencies.

A quick example would be https://github.com/PokeMMO/gdx-jnigen/commit/c9c41d3fc8f4751d1b72449a14383423d050b62e

This would be a slightly breaking change for libgdx as a whole, which replaces GdxRuntimeExceptions with regular RuntimeExceptions. (Or potentially a new custom typed JnigenRuntimeException)

Would this exception class change be an issue?

Edit: I guess we could also just move GdxRuntimeException to this instead of gdx base. I don't really like that idea, but it would work and not break anything.

**Comment by Tom-Ski** [comment]
A local clone of GdxRuntimeException? Or move it out of gdx core to here?

**Comment by MobiDevelop** [comment]
I'd think a new specific runtime exception would be fine.
