### ISSUE TITLE
Failed to find MinGW Compiler

### ISSUE THREAD

**Issue by AN3Orik** [libgdx/gdx-jnigen#44]
Currently plugin generate script whos can't find installed minGW compiler binary at Windows - as result: compilation failed.

Part of verbose ant build log output:

[available] Searching C:\mingw64\bin  _(Compiler binary 100% exist here)_
[available] Unable to find x86_64-w64-mingw32-g++ _(Seams build script try to find binary without exe extension)_

**Comment by Berstanio** [comment]
You can set a compiler prefix like this:
```
jnigen {
    ...
    add(Windows, x32) {
        compilerSuffix = ".exe"
    }
    add(Windows, x64) {
        compilerSuffix = ".exe"
    }
}
```
Could you try, whether that resolves your issue?

**Comment by AN3Orik** [comment]
Yeah, set forcibly suffix works. Thanks!
