### ISSUE TITLE
Windows Cross-Compile

### ISSUE THREAD

**Issue by AN3Orik** [libgdx/gdx-jnigen#45]
Hi there.
Its a possible to make cross builds for *nix from windows by default ant tasks generated by plugin or i must compile win lib at Windows and *nix at Linux separately?

**Comment by Tom-Ski** [comment]
You can cross compile from windows for specific platforms, but not all. 3.0.0 makes this more comfortable, and you also have options with MSVC toolchains.

we also have an easier way to setup to run on GHA, so you can use that if you dont have other platforms.
