### ISSUE TITLE
Add new CPU architecture

### ISSUE THREAD

**Issue by wangchenguang123** [libgdx/gdx-jnigen#49]
When I want to add a new form of CPU architecture to this project, how can I test its success

**Comment by SimonIT** [comment]
If you run `./gradlew build` (or just `./gradlew test`) on a computer with the new architecture, it will do all the jnigen magic and run it afterwords. If it is successful, something like this:
```
boolean: true
byte: 1
char: �
short: 3
int: 4
long: %
float: 6.000000
double: 0
byteBuffer: 8
bool[0]: false
char[0]:
short[0]: 10
int[0]: 11
long[0]: %
float[0]: 13.000000
double[0]: 14.000000
string: Hurray fuck this nuts
```
will appear in the log

**Comment by wangchenguang123** [comment]
> If you run `./gradlew build` (or just `./gradlew test`) on a computer with the new architecture, it will do all the jnigen magic and run it afterwords. If it is successful, something like this:
> 
> ```
> boolean: true
> byte: 1
> char: �
> short: 3
> int: 4
> long: %
> float: 6.000000
> double: 0
> byteBuffer: 8
> bool[0]: false
> char[0]:
> short[0]: 10
> int[0]: 11
> long[0]: %
> float[0]: 13.000000
> double[0]: 14.000000
> string: Hurray fuck this nuts
> ```
> 
> will appear in the log

ok thank you for your reply when i try to change some for new arch LoongArch like this。but i faifed do ./gradlew test 
i will continue try to find error about this
![图片](https://github.com/libgdx/gdx-jnigen/assets/56055887/a3f428ef-b6d4-42b6-ae06-eca4fbe1b683)
![图片](https://github.com/libgdx/gdx-jnigen/assets/56055887/891ac2f5-cd97-45c7-9b98-f0aac3504ccd)

**Comment by wangchenguang123** [comment]
> If you run `./gradlew build` (or just `./gradlew test`) on a computer with the new architecture, it will do all the jnigen magic and run it afterwords. If it is successful, something like this:
> 
> ```
> boolean: true
> byte: 1
> char: �
> short: 3
> int: 4
> long: %
> float: 6.000000
> double: 0
> byteBuffer: 8
> bool[0]: false
> char[0]:
> short[0]: 10
> int[0]: 11
> long[0]: %
> float[0]: 13.000000
> double[0]: 14.000000
> string: Hurray fuck this nuts
> ```
> 
> will appear in the log

ok thank you for your reply when i try to change some for new arch LoongArch like this。but i faifed do ./gradlew test
i will continue try to find error about this
![图片](https://github.com/libgdx/gdx-jnigen/assets/56055887/c528a61b-832d-4e43-9f4f-085388873f71)
![图片](https://github.com/libgdx/gdx-jnigen/assets/56055887/5a8c53fe-d16a-4b59-88e1-40ed7de08bfe)

**Comment by SimonIT** [comment]
You can find a more detailed exception in `gdx-jnigen/build/reports/tests/test/classes/com.badlogic.gdx.jnigen.JniGenTest.html`. Probably are some tools missing

**Comment by Berstanio** [comment]
https://github.com/libgdx/gdx-jnigen/pull/54 has been merged
